name: hello

on:
  push:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: build
      run: encho "Testes feitos a buildar"
    steps:
      - name: test
        needs: build
        run: echo "A correr testes"


